### ISSUE TITLE
Unable to compile with wxWidgets 3.2.3 and vc15

### ISSUE THREAD

**Issue by starmate** [imReker/wxWebViewBlink#10]
Hello,

Seems to be great! I tried to include this to my project but I get LNK2001 issue sunresolved external symbol "char const * const wxWebViewBackendMiniBlink"

Could you give me any directions in order to fix this?

Regards,

Jon

**Comment by imReker** [comment]
Please follow the usage section in Readme and make sure `WebViewMiniBlink.cpp`, `WebViewMiniBlink.h` and `wkedefine.h` is included in your project.
